name: nivaldomotos
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.5
  carousel_pro: ^1.0.0
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.11.1+12
  font_awesome_flutter: ^8.8.1
  google_maps_flutter: ^0.5.27+1
  flare_flutter: ^2.0.1
  date_format: ^1.0.8
  page_transition: ^1.1.5
  flutter_masked_text: ^0.8.0
  flutter_open_whatsapp: ^0.1.2
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  image_path: 'assets/images/icon_app.png'
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/images/
    - assets/maps/
    - assets/animators/
    - assets/icons/

  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.otf

    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraBold.otf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.otf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.otf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf